[package]
name = "baxe-derive"
version = "0.1.1"
edition = "2021"
description = "Procedural macro for Baxe library."
license = "MIT"
repository = "https://github.com/iltumio/baxe"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.87"
quote = "1.0.37"
proc-macro2 = "1.0.89"
